<?php

include('connection_config.php');

$conn = new mysqli($servername, $username, $password,"Video");

$sql="CREATE TABLE ALL(
	ID INT(7) 	NOT NULL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL,
	Url VARCHAR(50) NOT NULL
	)";
$conn->query($sql);

$Names=array('C Programming Tutorial - 1 - Introduction',
'C Programming Tutorial - 2 - Setting Up Code Blocks',
'C Programming Tutorial - 3 - How Computer Programs Work',
'C Programming Tutorial - 4 - Print Text on the Screen',
'C Programming Tutorial - 5 - Comments',
'C Programming Tutorial - 6 - Conversion Characters',
'C Programming Tutorial - 7 - Variables',
'C Programming Tutorial - 8 - String Terminator',
'C Programming Tutorial - 9 - I Need Arrays',
'C Programming Tutorial - 10 - Creating a Header File',
'C Programming Tutorial - 11 - Getting Input with scanf',
'C Programming Tutorial - 12 - Math Operators',
'C Programming Tutorial - 13 - Cats Love Bagels',
'C Programming Tutorial - 14 - Calculating the Average Age',
'C Programming Tutorial - 15 - How to Calculate Interest',
'C Programming Tutorial - 16 - Typecasting',
'C Programming Tutorial - 17 - Making Decisions Using if Statements',
'C Programming Tutorial - 18 - Nesting if Statements',
'C Programming Tutorial - 19 - if else',
'C Programming Tutorial - 20 - What about more than two choices?',
'C Programming Tutorial - 21 - Dont Beat Up Little Kids',
'C Programming Tutorial - 22 - or',
'C Programming Tutorial - 23 - Shorthand if else',
'C Programming Tutorial - 24 - Increment Operator',
'C Programming Tutorial - 25 - while Loops',
'C Programming Tutorial - 26 - do while Loops',
'C Programming Tutorial - 27 - for Loop',
'C Programming Tutorial - 28 - How to Make a Table',
'C Programming Tutorial - 29 - break',
'C Programming Tutorial - 30 - continue',
'C Programming Tutorial - 31 - switch',
'C Programming Tutorial - 32 - A Few Cool Character Functions',
'C Programming Tutorial - 33 - isupper and Challenge #1!',
'C Programming Tutorial - 34 - strcat and strcpy',
'C Programming Tutorial - 35 - puts and gets',
'C Programming Tutorial - 36 - Rounding Numbers',
'C Programming Tutorial - 37 - Absolute Value with abs',
'C Programming Tutorial - 38 - Random Number Generator with rand',
'C Programming Tutorial - 39 - int and float Arrays',
'C Programming Tutorial - 40 - Why I am Banned from Fantasy Hockey',
'C Programming Tutorial - 41 - Sorting Arrays',
'C Programming Tutorial - 42 - Pointers',
'C Programming Tutorial - 43 - Dereference Pointer',
'C Programming Tutorial - 44 - Arrays and Pointers',
'C Programming Tutorial - 45 - Strings and Pointers',
'C Programming Tutorial - 46 - Problems with String Lengths',
'C Programming Tutorial - 47 - The Heap',
'C Programming Tutorial - 48 - Creating an Expandable Program using the Heap',
'C Programming Tutorial - 49 - Structures',
'C Programming Tutorial - 50 - Writing Files in C',
'C Programming Tutorial - 51 - How to Read Files',
'C Programming Tutorial - 52 - Append to File',
'C Programming Tutorial - 53 - Random File Access',
'C Programming Tutorial - 54 - Functions',
'C Programming Tutorial - 55 - Global vs Local Variables',
'C Programming Tutorial - 56 - Passing Arguments to Functions',
'C Programming Tutorial - 57 - Return Values',
'C Programming Tutorial - 58 - Pass by Reference vs Pass by Value',

'[Python] 01 Welcome',
'[Python] 02 Understanding prerequisites for Python',
'[Python] 03 Using the exercise files',
'[Python] 04 Getting started with Hello World',
'[Python] 05 Selecting code with conditionals',
'[Python] 06 Repeating code with a loop',
'[Python] 07 Reusing code with a function',
'[Python] 08 Creating sequences with generator functions',
'[Python] 09 Reusing code and data with a class',
'[Python] 10 Greater reusability with inheritance and polymorphism',
'[Python] 11 Handling errors with exceptions',
'[Python] 12 Installing Python 3 and Eclipse for Mac',
'[Python] 13 Installing Python 3 and Eclipse for Windows',
'[Python] 14 Creating a main script',
'[Python] 15 Understanding whitespace in Python',
'[Python] 16 Commenting code',
'[Python] 17 Assigning values',
'[Python] 18 Selecting code and values with conditionals',
'[Python] 19 Creating and using functions',
'[Python] 20 Creating and using objects',
'[Python] 21 Understanding variables and objects in Python',
'[Python] 22 Distinguishing mutable and immutable objects',
'[Python] 23 Using numbers',
'[Python] 24 Using strings',
'[Python] 25 Aggregating values with lists and tuples',
'[Python] 26 Creating associative lists with dictionaries',
'[Python] 27 Finding the type and identity of a variable',
'[Python] 28 Specifying logical values with True and False',
'[Python] 29 Selecting code with if and else conditional statements',
'[Python] 30 Setting multiple choices with elif',
'[Python] 31 Understanding other strategies for multiple choices',
'[Python] 32 Using the conditional expression',
'[Python] 33 Creating loops with while',
'[Python] 34 Iterating with for',
'[Python] 35 Enumerating iterators',
'[Python] 36 Controlling loop flow with break continue and else',
'[Python] 37 Performing simple arithmetic',
'[Python] 38 Operating on bitwise values',
'[Python] 39 Comparing values',
'[Python] 40 Operating on Boolean values',
'[Python] 41 Operating on parts of a container with the slice operator',
'[Python] 42 Understanding operator precedence',
'[Python] 43 Using the re module',
'[Python] 44 Searching with regular expressions',
'[Python] 45 Replacing with regular expressions',
'[Python] 46 Reusing regular expressions with re compile',
'[Python] 47 Learning how exceptions work',
'[Python] 48 Handling exceptions',
'[Python] 49 Raising exceptions',
'[Python] 50 Defining functions',
'[Python] 51 Using lists of arguments',
'[Python] 52 Using named function arguments',
'[Python] 53 Returning values from functions',
'[Python] 54 Creating a sequence with a generator function',
'[Python] 55 Understanding classes and objects',
'[Python] 56 Using methods',
'[Python] 57 Using object data',
'[Python] 58 Understanding inheritance',
'[Python] 59 Applying polymorphism to classes',
'[Python] 60 Using generators',
'[Python] 61 Using decorators',
'[Python] 62 Understanding strings as objects',
'[Python] 63 Working with common string methods',
'[Python] 64 Formatting strings with str format',
'[Python] 65 Splitting and joining strings',
'[Python] 66 Finding and using standard string methods',
'[Python] 67 Creating sequences with tuples and lists',
'[Python] 68 Operating on sequences with built in methods',
'[Python] 69 Organizing data with dictionaries',
'[Python] 70 Operating on character data with bytes and byte arrays',
'[Python] 71 Opening files',
'[Python] 72 Reading and writing text files',
'[Python] 73 Reading and writing binary files',
'[Python] 74 Creating a database with SQLite 3',
'[Python] 75 Creating retrieving updating and deleting records',
'[Python] 76 Creating a database object',
'[Python] 77 Using standard library modules',
'[Python] 78 Finding third party modules',
'[Python] 79 Creating a module',
'[Python] 80 Dealing with syntax errors',
'[Python] 81 Dealing with runtime errors',
'[Python] 82 Dealing with logical errors',
'[Python] 83 Using unit tests',
'[Python] 84 Normalizing a database interface',
'[Python] 85 Deconstructing a database application',
'[Python] 86 Displaying random entries from a database',
'[Python] 87 Goodbye',

'1. Welcome to Java',
'2. Is this course for you: Java',
'3. Using the exercise files',
'4. The history of Java',
'5. Understanding the principles of Java',
'6. Java compilation and syntax',
'7. Choosing a development environment',
'8. Installing Java on Windows',
'9. Installing Eclipse on Windows',
'10. Exploring Java on Mac OS X Leopard and Snow Leopard',
'11. Installing Java on Mac OS X Lion',
'12. Installing Eclipse on Mac OS X',
'13. Creating a Hello World application',
'14. Exploring the Eclipse IDE',
'15. Compiling and running from the command line',
'16 Passing arguments to the application',
'17. Using the Java API documentation',
'18. Memory management and garbage collection',
'19. Everything is an object',
'20. Declaring and initializing variables',
'21. Working with numbers',
'22. Converting numeric values',
'23. Understanding operators',
'24. Working with character values',
'25 Working with boolean values',
'26. Outputting primitive values as strings',
'27. Creating a simple calculator application',
'28. Writing conditional code',
'29. Using the switch statement',
'30. Repeating code blocks with loops',
'31. Creating reusable code with methods',
'32. Declaring methods with arguments',
'33. Overloading method names with different signatures',
'34. Passing arguments by reference or by value',
'35. Creating a more complex calculator application',
'36. Using the String class',
'37. Building strings with StringBuilder',
'38. Parsing string values',
'39. Working with date values',
'40. Understanding compile-time vs. runtime errors',
'41. Handling exceptions with try-catch',

'1. Algorithmic Thinking, Peak Finding',
'2. Models of Computation, Document Distance ',
'3. Insertion Sort, Merge Sort ',
'4. Heaps and Heap Sort ',
'5. Binary Search Trees, BST Sort',
'6. AVL Trees, AVL Sort',
'7. Counting Sort, Radix Sort, Lower Bounds for Sorting',
'8. Hashing with Chaining',
'9. Table Doubling, Karp-Rabin',
'10. Open Addressing, Cryptographic Hashing',
'11. Integer Arithmetic, Karatsuba Multiplication',
'12. Square Roots, Newton\'s Method',
'13. Breadth-First Search (BFS) ',
'14. Depth-First Search (DFS), Topological Sort ',
'15. Single-Source Shortest Paths Problem ',
'16. Dijkstra ',
'17. Bellman-Ford ',
'18. Speeding up Dijkstra ',
'19. Dynamic Programming I: Fibonacci, Shortest Paths ',
'20. Dynamic Programming II: Text Justification, Blackjack ',
'21. DP III: Parenthesization, Edit Distance, Knapsack ',
'22. DP IV: Guitar Fingering, Tetris, Super Mario Bros. ',
'23. Computational Complexity ',
'24. Topics in Algorithms Research ',
'R1. Asymptotic Complexity, Peak Finding ',
'R2. Python Cost Model, Document Distance ',
'R3. Document Distance, Insertion and Merge Sort ',
'R5. Recursion Trees, Binary Search Trees ',
'R6. AVL Trees ',
'R7. Comparison Sort, Counting and Radix Sort ',
'R8. Simulation Algorithms ',
'R9. Rolling Hashes, Amortized Analysis ',
'Recitation 9b: DNA Sequence Matching ',
'R10. Quiz 1 Review ',
'R11. Principles of Algorithm Design ',
'R12. Karatsuba Multiplication, Newton\'s Method ',
'R13. Breadth-First Search (BFS) ',
'R14. Depth-First Search (DFS) ',
'R15. Shortest Paths ',
'R16. Rubik\'s Cube, StarCraft Zero ',
'R18. Quiz 2 Review ',
'R19. Dynamic Programming: Crazy Eights, Shortest Path ',
'R20. Dynamic Programming: Blackjack ',
'R22. Dynamic Programming: Dance Dance Revolution ',
'R21. Dynamic Programming: Knapsack Problem ',
'R23. Computational Complexity ',
'R24. Final Exam Review ',

'Learn GIMP Tutorial - Day 1 - Size Crop Rotate and Flip ',
'Learn GIMP Tutorial - Day 2 - Logo Design ',
'Learn GIMP Tutorial - Day 3 - Selection Tools ',
'Learn Gimp Tutorial - Day 4 - Path Tool ',
'Learn GIMP Tutorial - Day 5 - Create a Vignette with Quickmask ',
'Learn GIMP Tutorial - Day 6 - How to Remove Red Eye ',
'Learn GIMP Tutorial - Day 7 - How to Draw a Straight Line in Gimp ',
'Learn GIMP Tutorial - Day 8 - Layer Mask in Gimp ',
'Learn GIMP Tutorial - Day 9 - How to Swap Faces in GIMP ',
'Learn GIMP Tutorial - Day 10 - How to Clean Up Faces ',
'Learn GIMP Tutorial - Day 11 - User Interface and Toolbar Layout ',
'Learn GIMP Tutorial - Day 12 - Threshold Aliasing and Curves ',
'Learn Gimp Tutorial - Day 13 - Change Background Color ',
'Learn GIMP Tutorial - Day 14 - Sketch Effect ',
'Learn GIMP Tutorial - Day 15 - Custom Brushes ',
'Gimp Tutorial - 16 - Water Reflection in GIMP ',
'GIMP Tutorial - 17 - HDR Photo With GIMP ',

'PHP Video Tutorial for Beginners With Examples - 1 - PHP Overview ',
'PHP Video Tutorial for Beginners With Examples - 2 - Windows Installation ',
'PHP Video Tutorial for Beginners With Examples - 3 - First Steps ',
'PHP Video Tutorial for Beginners With Examples - 4 - Exploring Data Types Part - 1 ',
'PHP Video Tutorial for Beginners With Examples - 5 - Exploring Data Types Part - 2 ',
'PHP Video Tutorial for Beginners With Examples - 6 - Control Structures - Logical Expressions',
'PHP Video Tutorial for Beginners With Examples - 7 - Control Structures - Loops ',
'PHP Video Tutorial for Beginners With Examples - 8 - User-Defined Functions ',
'PHP Video Tutorial for Beginners With Examples - 9 - Debugging ',
'PHP Video Tutorial for Beginners With Examples - 10 - Building Web Pages with PHP ',
'PHP Video Tutorial for Beginners With Examples - 11 - Building Web Pages with PHP Part - 2 ',
'PHP Video Tutorial for Beginners With Examples - 12 - Working with Forms and Form Data Part - 1',
'PHP Video Tutorial for Beginners With Examples - 13 - Working with Forms and Form Data Part - 2 ',
'PHP Video Tutorial for Beginners With Examples - 14 - Working with Cookies and Sessions ',
'PHP Video Tutorial for Beginners With Examples - 15 - MySQL Basics ',
'PHP Video Tutorial for Beginners With Examples - 16 - Using PHP to Access MySQL Part - 1 ',
'PHP Video Tutorial for Beginners With Examples - 17 - Using PHP to Access MySQL Part - 2 ',
'PHP Video Tutorial for Beginners With Examples - 18 - Building a Content Management System (CMS) ',
'PHP Video Tutorial for Beginners With Examples - 19 - Using Site Navigation to Choose Content ',
'PHP Video Tutorial for Beginners With Examples - 20 - Application CRUD Part - 1 ',
'PHP Video Tutorial for Beginners With Examples - 21 - Application CRUD Part - 2 ',
'PHP Video Tutorial for Beginners With Examples - 22 - Application CRUD Part - 3 ',
'PHP Video Tutorial for Beginners With Examples - 23 - Application CRUD Part - 4 ',
'PHP Video Tutorial for Beginners With Examples - 24 - Building the Public Area Part - 1 ',
'PHP Video Tutorial for Beginners With Examples - 25 - Building the Public Area Part - 2 ',
'PHP Video Tutorial for Beginners With Examples - 26 - Regulating Page Access Part - 1 ',
'PHP Video Tutorial for Beginners With Examples - 27 - Regulating Page Access Part - 2 ',
'PHP Video Tutorial for Beginners With Examples - 28 - Regulating Page Access Part - 3 ',
'PHP Video Tutorial for Beginners With Examples - 29 - Conclusion ',
'LaTeX Tutorial 01 your first \"hello world\" document',
'LaTeX Tutorial 02 bold, italic, fixed-width font, and commenting',
'LaTeX Tutorial 03 numbered lists with and without subitems.',
'LaTeX Tutorial 04 Subscripts and Superscripts',
'LaTeX Tutorial 05 using the align environment',
'LaTeX Tutorial 06 matrices','LaTeX Tutorial 07 typing fractions, square roots, and integrals',
'LaTeX Tutorial 07 typing fractions, square roots, and integrals',
'LaTeX Tutorial 08 the difference between in-line, centered, and aligned math',);






$Links=array(
'https://www.youtube.com/embed/2NWeucMKrLI',
'https://www.youtube.com/embed/3DeLiClDd04',
'https://www.youtube.com/embed/iWx3yyFMWQA',
'https://www.youtube.com/embed/oSpmApiUsHw',
'https://www.youtube.com/embed/oX2FpFYXE38',
'https://www.youtube.com/embed/To7WA4ijQQ0',
'https://www.youtube.com/embed/k1ur8rX-DQQ',
'https://www.youtube.com/embed/LEHaSSYreeo',
'https://www.youtube.com/embed/7F-Q2oVBYKk',
'https://www.youtube.com/embed/1EeetMPACMI',
'https://www.youtube.com/embed/hSHFjPvqFjw',
'https://www.youtube.com/embed/T3sj5iTK_0M',
'https://www.youtube.com/embed/rubhV7Bu34E',
'https://www.youtube.com/embed/cgkGwRonMU4',
'https://www.youtube.com/embed/_oqmPcqWHlE',
'https://www.youtube.com/embed/ohVRskLlHqM',
'https://www.youtube.com/embed/PXwWoL0IG5A',
'https://www.youtube.com/embed/FtZ1YgSFqs0',
'https://www.youtube.com/embed/KgVzRmUPsdo',
'https://www.youtube.com/embed/DZ0ZXipUx-A',
'https://www.youtube.com/embed/PO3BibcbkK8',
'https://www.youtube.com/embed/brC8O7AeCFA',
'https://www.youtube.com/embed/pze0PKwdfl0',
'https://www.youtube.com/embed/nNSn1uVNyiU',
'https://www.youtube.com/embed/7pAXm7WEA2I',
'https://www.youtube.com/embed/eU6no0EEJM0',
'https://www.youtube.com/embed/FPjLbPu5BsQ',
'https://www.youtube.com/embed/Y17-tKQXrxs',
'https://www.youtube.com/embed/JKVc02-GmGs',
'https://www.youtube.com/embed/4XaaIGBdhaw',
'https://www.youtube.com/embed/qZRP5hKGHrs',
'https://www.youtube.com/embed/IJp4KU7SiuQ',
'https://www.youtube.com/embed/PVTDEOeSP88',
'https://www.youtube.com/embed/-SSsm0gVu3o',
'https://www.youtube.com/embed/yvpCxgV3AZo',
'https://www.youtube.com/embed/XxwGqFaxJK0',
'https://www.youtube.com/embed/VcEHkVStszM',
'https://www.youtube.com/embed/QCe2ks9b8YI',
'https://www.youtube.com/embed/IPYA3b3_nyk',
'https://www.youtube.com/embed/_LDN79j5H5s',
'https://www.youtube.com/embed/6qiNJWw5aLI',
'https://www.youtube.com/embed/5BpYD7TxvKU',
'https://www.youtube.com/embed/vjq-13YADeI',
'https://www.youtube.com/embed/sq6n8dL117c',
'https://www.youtube.com/embed/-9fqo94G6YU',
'https://www.youtube.com/embed/Y7R8m-10GJc',
'https://www.youtube.com/embed/Buq071iqYAM',
'https://www.youtube.com/embed/gWppLYaCICM',
'https://www.youtube.com/embed/VMFKz7Klx7I',
'https://www.youtube.com/embed/38I_AUMpKpQ',
'https://www.youtube.com/embed/8nIilb2kiSU',
'https://www.youtube.com/embed/Hxhbp1WSDJA',
'https://www.youtube.com/embed/yPYrxbkY2rk',
'https://www.youtube.com/embed/lv5IDF7dmBk',
'https://www.youtube.com/embed/sAj_Jrqrg5g',
'https://www.youtube.com/embed/_oyuKw3vBf8',
'https://www.youtube.com/embed/_oyuKw3vBf8',
'https://www.youtube.com/embed/wAmq8eIkdI8',
'https://www.youtube.com/embed/DmJJTa2snk0',
'https://www.youtube.com/embed/Y3cLZN3KF9o',
'https://www.youtube.com/embed/Y3cLZN3KF9o',
'https://www.youtube.com/embed/aZ3cQ49ZtR8',
'https://www.youtube.com/embed/kUX9BMfNIgY',
'https://www.youtube.com/embed/jEbobcnCc_A',
'https://www.youtube.com/embed/36QE-85QRdA',
'https://www.youtube.com/embed/T2HFDiSpZX4',
'https://www.youtube.com/embed/pa2NkcRPHZM',
'https://www.youtube.com/embed/6YjyC4hWJfk',
'https://www.youtube.com/embed/0ADErsK8Afo',
'https://www.youtube.com/embed/MaRsp07UY68',
'https://www.youtube.com/embed/l5FyN2YoYWw',
'https://www.youtube.com/embed/nQKhrnMr7ag',
'https://www.youtube.com/embed/LxXhTX4Bp4A',
'https://www.youtube.com/embed/8faov-1b594',
'https://www.youtube.com/embed/NQvLNQjZGuE',
'https://www.youtube.com/embed/PxOVcHjmM8M',
'https://www.youtube.com/embed/iRv06VNT6o4',
'https://www.youtube.com/embed/2-6BaYFW0eU',
'https://www.youtube.com/embed/QxMfk90PVKI',
'https://www.youtube.com/embed/efvvbW5H5Ks',
'https://www.youtube.com/embed/we4eB2rcHnE',
'https://www.youtube.com/embed/EKSCylCEPhM',
'https://www.youtube.com/embed/wWDBGN1QFhw',
'https://www.youtube.com/embed/_1J5gCVVTb8',
'https://www.youtube.com/embed/pnKTW1keXvE',
'https://www.youtube.com/embed/5-VH73t5GaY',
'https://www.youtube.com/embed/c3_kK_Q9td4',
'https://www.youtube.com/embed/Zn09QQfLAcg',
'https://www.youtube.com/embed/s9xMvY7lvpw',
'https://www.youtube.com/embed/Ovg58qcCIA8',
'https://www.youtube.com/embed/YgoR5cs8pAs',
'https://www.youtube.com/embed/awbzQGBElmM',
'https://www.youtube.com/embed/T77Zf9b-Iu0',
'https://www.youtube.com/embed/gMHjQloKsKQ',
'https://www.youtube.com/embed/41U6l0SO_p8',
'https://www.youtube.com/embed/lQNln_G-Coo',
'https://www.youtube.com/embed/KQ1gVJ5Zwa4',
'https://www.youtube.com/embed/wB5uqnYNBtA',
'https://www.youtube.com/embed/1LLy9Bu-gNk',
'https://www.youtube.com/embed/tHW6XA4XAxs',
'https://www.youtube.com/embed/KMWJuhoVY6k',
'https://www.youtube.com/embed/3PcUPnemBQc',
'https://www.youtube.com/embed/XPkJe9I8FPE',
'https://www.youtube.com/embed/bA8dBKRwbns',
'https://www.youtube.com/embed/q7PvIEcBZVY',
'https://www.youtube.com/embed/H2RYuvcsy-M',
'https://www.youtube.com/embed/wOuajjin__8',
'https://www.youtube.com/embed/gwJ7aAqOf28',
'https://www.youtube.com/embed/DWWtmjSE5j4',
'https://www.youtube.com/embed/JzRSymwVTMk',
'https://www.youtube.com/embed/xYgdc_KHg1I',
'https://www.youtube.com/embed/OLOeigoh-Vc',
'https://www.youtube.com/embed/ulDBus03uRQ',
'https://www.youtube.com/embed/JrE-mojZ3y0',
'https://www.youtube.com/embed/c1-eyxi75yY',
'https://www.youtube.com/embed/fqfDjhd1fg8',
'https://www.youtube.com/embed/Wgs_O90doKw',
'https://www.youtube.com/embed/ULVyV_mf6_4',
'https://www.youtube.com/embed/kvk-m6Xi99U',
'https://www.youtube.com/embed/lfzCFsJZckI',
'https://www.youtube.com/embed/ol7JKqCnfjk',
'https://www.youtube.com/embed/Nfbb9-AeTr4',
'https://www.youtube.com/embed/uJCgaPsuG8Y',
'https://www.youtube.com/embed/1SKpNWEesNA',
'https://www.youtube.com/embed/MIP_WKeqxi4',
'https://www.youtube.com/embed/7T4NZNWgI50',
'https://www.youtube.com/embed/mv9xpWn6azU',
'https://www.youtube.com/embed/MBSVfTGNClU',
'https://www.youtube.com/embed/zpAY0IO53C8',
'https://www.youtube.com/embed/d4yXOKyQ5Xk',
'https://www.youtube.com/embed/1Gs5QHpXhjM',
'https://www.youtube.com/embed/n-Rtfd1Vv_M',
'https://www.youtube.com/embed/F7V_IebN-OU',
'https://www.youtube.com/embed/APXd_knD4II',
'https://www.youtube.com/embed/b5WfkG68Q-k',
'https://www.youtube.com/embed/K14zR44LKGw',
'https://www.youtube.com/embed/f-VZqbSPzRI',
'https://www.youtube.com/embed/8AR9KjBhVIM',
'https://www.youtube.com/embed/VW5yQ_kzEUE',
'https://www.youtube.com/embed/rK8lHrwi25U',
'https://www.youtube.com/embed/32SmdtO5wKI',
'https://www.youtube.com/embed/y-MMznhfrDo',
'https://www.youtube.com/embed/rR9rfyDrIR8',
'https://www.youtube.com/embed/b-57prdSwOU',
'https://www.youtube.com/embed/sjpD1yhx1zY',
'https://www.youtube.com/embed/2FnO7MqiNyE',
'https://www.youtube.com/embed/a8AwhtSRX04',
'https://www.youtube.com/embed/_H-mEWjDFUU',
'https://www.youtube.com/embed/S6yPUuqwYK4',
'https://www.youtube.com/embed/GWvdZDS2_pQ',
'https://www.youtube.com/embed/Tt0ROwsN_4U',
'https://www.youtube.com/embed/gYLwO0ezN34',
'https://www.youtube.com/embed/tSnYkjtIQTw',
'https://www.youtube.com/embed/gHBhB-xobL8',
'https://www.youtube.com/embed/uD6bqfi1bbI',
'https://www.youtube.com/embed/8ma4skz4j_8',
'https://www.youtube.com/embed/6oCBwY-bOA8',
'https://www.youtube.com/embed/UUfmSJ1TKWc',
'https://www.youtube.com/embed/D2wgJ5smavA',
'https://www.youtube.com/embed/j7b-n9EJUMA',
'https://www.youtube.com/embed/AJu6IwMKQyw',
'https://www.youtube.com/embed/E3wCmOo5Mrc',
'https://www.youtube.com/embed/pDNdVWhRQTw',
'https://www.youtube.com/embed/CStLITAwMMw',
'https://www.youtube.com/embed/cgAY2lAwcgs',
'https://www.youtube.com/embed/MVR9uRDGlzw',
'https://www.youtube.com/embed/xhoLU8bbAxI',
'https://www.youtube.com/embed/HO3f-qKXIz8',
'https://www.youtube.com/embed/SBLcApBJIog',
'https://www.youtube.com/embed/RVrud6mkeM4',
'https://www.youtube.com/embed/vb7-zODRDco',
'https://www.youtube.com/embed/MT7FAKcBwCI',
'https://www.youtube.com/embed/JthiCEobhCI',
'https://www.youtube.com/embed/EgJHDbDaOec',
'https://www.youtube.com/embed/AKJviTAuLBo',
'https://www.youtube.com/embed/MH9SmMpN9IM',
'https://www.youtube.com/embed/23nFLkyca1c',
'https://www.youtube.com/embed/nfsw5O3lhXY',
'https://www.youtube.com/embed/b3MkobmFvP8',
'https://www.youtube.com/embed/xPylJOCUG9A',
'https://www.youtube.com/embed/OShx9q9iQPM',
'https://www.youtube.com/embed/JHjXDicqaA8',
'https://www.youtube.com/embed/NVoF8SlDJyA',
'https://www.youtube.com/embed/f93TQxGwEDA',
'https://www.youtube.com/embed/f93TQxGwEDA',
'https://www.youtube.com/embed/TCJqek-_eZ0',
'https://www.youtube.com/embed/C_3HVBEHtgM',
'https://www.youtube.com/embed/HtSuA80QTyo',
'https://www.youtube.com/embed/Zc54gFhdpLA',
'https://www.youtube.com/embed/Kg4bqzAqRBM',
'https://www.youtube.com/embed/B7hVxCmfPtM',
'https://www.youtube.com/embed/9Jry5-82I68',
'https://www.youtube.com/embed/FNeL18KsWPc',
'https://www.youtube.com/embed/Nz1KZXbghj8',
'https://www.youtube.com/embed/0M_kIqhwbFo',
'https://www.youtube.com/embed/BRO7mVIFt08',
'https://www.youtube.com/embed/rvdJDijO2Ro',
'https://www.youtube.com/embed/eCaXlAaN2uE',
'https://www.youtube.com/embed/2YeJ-5UAke8',
'https://www.youtube.com/embed/s-CYnVz-uh4',
'https://www.youtube.com/embed/AfSk24UTFS8',
'https://www.youtube.com/embed/Aa2sqUhIn-E',
'https://www.youtube.com/embed/2E7MmKv0Y24',
'https://www.youtube.com/embed/ozsuci5pIso',
'https://www.youtube.com/embed/CHvQ3q_gJ7E',
'https://www.youtube.com/embed/OQ5jsbhAv_M',
'https://www.youtube.com/embed/ENyox7kNKeY',
'https://www.youtube.com/embed/ocZMDMZwhCY',
'https://www.youtube.com/embed/tp4_UXaVyx8',
'https://www.youtube.com/embed/moPtwq_cVH8',
'https://www.youtube.com/embed/dU40AvBURDQ',
'https://www.youtube.com/embed/P7frcB_-g4w',
'https://www.youtube.com/embed/QFcyt8fgQMU',
'https://www.youtube.com/embed/4iXLnF3hExw',
'https://www.youtube.com/embed/r5pXu1PAUkI',
'https://www.youtube.com/embed/IWzYoXKaRIc',
'https://www.youtube.com/embed/9bkvws_vqLU',
'https://www.youtube.com/embed/eGSXsaJ-BlY',
'https://www.youtube.com/embed/w6nuXg0BISo',
'https://www.youtube.com/embed/-DwGrJ8JxDc',
'https://www.youtube.com/embed/-FElVPKykgw',
'https://www.youtube.com/embed/a_otxyu0mSQ',
'https://www.youtube.com/embed/JRgIXyEPnbA',
'https://www.youtube.com/embed/5JxShDZ_ylo',
'https://www.youtube.com/embed/C5SPsY72_CM',
'https://www.youtube.com/embed/mQSp6VmfakA',
'https://www.youtube.com/embed/oRpERQA4Vik',
'https://www.youtube.com/embed/sPuazUPiV1k',
'https://www.youtube.com/embed/IFrvgSvZA0I',
'https://www.youtube.com/embed/jZbkToeNK2g',
'https://www.youtube.com/embed/PptQgy89cN8',
'https://www.youtube.com/embed/wFP5VHGHFdk',
'https://www.youtube.com/embed/t5Wxk96QjUk',
'https://www.youtube.com/embed/hkAONP0aC9w',
'https://www.youtube.com/embed/bqF4X1bs6NA',
'https://www.youtube.com/embed/ywQ9zJKJQSI',
'https://www.youtube.com/embed/LxzWcB1JOlo',
'https://www.youtube.com/embed/bG3mo0UvM3k',
'https://www.youtube.com/embed/7Uur9IWiPX0',
'https://www.youtube.com/embed/WsUNWfXjIzI',
'https://www.youtube.com/embed/_WoGVIbyROE',
'https://www.youtube.com/embed/GHPj_upb4Fw',
'https://www.youtube.com/embed/1LZxnCPUICA',
'https://www.youtube.com/embed/_9LTLuMaMCI',
'https://www.youtube.com/embed/UyXtj5unYbM',
'https://www.youtube.com/embed/F7yX_301Gmk',
'https://www.youtube.com/embed/BpFo1DzGQ18',
'https://www.youtube.com/embed/vH_TN73QGMU',
'https://www.youtube.com/embed/Vfi2tv-lqdk',
'https://www.youtube.com/embed/B9ort7B7K3s',
'https://www.youtube.com/embed/CEKAze4aEd8',
'https://www.youtube.com/embed/1tpEPFL1bds',
'https://www.youtube.com/embed/HiNn3lsaw5U',
'https://www.youtube.com/embed/q38BlB9lOMw',
'https://www.youtube.com/embed/UVhS5wlXxds',
'https://www.youtube.com/embed/80tUJ1SQPqI',
'https://www.youtube.com/embed/x2N-owm0KUk',
'https://www.youtube.com/embed/recgp6C6_hE',
'https://www.youtube.com/embed/geV9MynUKGg',
'https://www.youtube.com/embed/OCZ14aUz620',
'https://www.youtube.com/embed/fvS_Ge9jAFU',
'https://www.youtube.com/embed/VkhfDMq0oxo',
'https://www.youtube.com/embed/OxZd6w_4XY0',
'https://www.youtube.com/embed/0UAOiC9GiEE',
'https://www.youtube.com/embed/gXkNHiyf7gs',
'https://www.youtube.com/embed/7t1ARhyZ_50',
'https://www.youtube.com/embed/_9FJPsCbHGQ',
'https://www.youtube.com/embed/6nn0B-5Q5IA',
'https://www.youtube.com/embed/aIKDjMXlFFA',
'https://www.youtube.com/embed/qFQA-sRjH7c',
'https://www.youtube.com/embed/uvRCcpfPqdk',
'https://www.youtube.com/embed/5Kht-RJecR0',
'https://www.youtube.com/embed/gdU3sljZ0Yo',
'https://www.youtube.com/embed/1ibQJhwLuZk',
'https://www.youtube.com/embed/8A3LqXSZrRY',
'https://www.youtube.com/embed/0v-a1lteFiI',
'https://www.youtube.com/embed/qSz4Y2wteg8',
'https://www.youtube.com/embed/mB8E4OY8G_Q',
'https://www.youtube.com/embed/PzAMrH4afSw',
'https://www.youtube.com/embed/eVzUDQXoO8c',
'https://www.youtube.com/embed/W_yPJsF1X18',
'https://www.youtube.com/embed/Hg9dZatXvF8',
'https://www.youtube.com/embed/mn9FfoYWz5k',
'https://www.youtube.com/embed/zxJf8ufaKPM',
'https://www.youtube.com/embed/tdBG39JD4gA',
'https://www.youtube.com/embed/xCk31_yDm18',
'https://www.youtube.com/embed/Xl1c_1yL47k',
'https://www.youtube.com/embed/-tu5l_n4byk');
for($i=0;$i<287;$i++)
{
$conn = new mysqli($servername, $username, $password,"Video");
$sql="INSERT INTO ALL(ID,Name,Url)
VALUES ($i+1,'$Names[$i]','$Links[$i]')";
$conn->query($sql);
}

?>
